### ISSUE TITLE
SKI and AKI need to be considered user input

### ISSUE THREAD

**Issue by matgnt** [eclipse-tractusx/daps-registration-service#33]
Hi team,

as part of a risk analysis of the DAPS server (see link for details)
https://github.com/Fraunhofer-AISEC/omejdn-server/issues/74

I found out, that SKI and AKI are loaded from the extension of the certificate. **In case of self-signed certificates,** this needs to be considered user input and should not be trusted directly.
https://github.com/eclipse-tractusx/daps-registration-service/blob/main/src/main/java/org/eclipse/tractusx/dapsreg/util/Certutil.java#L51
# Flow
![registration_service_client_id_attack_scenario](https://user-images.githubusercontent.com/198707/232835906-00dac0b2-6e52-42d5-9589-c09ad83b2cf3.png)

Since the clientId is not a secret and can be gathered from any EDC interaction (it is part of the DAPS token), this is not a secret. It could happen, that someone elses account / certificate is overwritten and this other party does not get a valid DAPS token any more.

I did not check all the portal checks which happen before the registration service is called. It is good though, that there are checks as well.

---
Matthias Binzer
Robert Bosch GmbH

**Comment by dvasunin** [comment]
We re-create SKI using public key from the certificate and compare it with SKI bundled. If they differ we deny request

**Comment by matgnt** [comment]
The fix mentioned by @dvasunin seems to be part of PR #46

**Comment by SebastianBezold** [comment]
#46 did indeed contain multiple fixes, but from commit messages it was not really clear, which change fixed what issue.
#50, #51 and #52 have been merged to fix the issues that are not related to this one here.
@dvasunin, will there be another dedicated PR to address the SKI topic?
