### ISSUE TITLE
Typo in INSTALL.md

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/daps-registration-service#37]
## Description

The instructions on how to install the Helm chart do contain a typo/[wrong reference](https://github.com/eclipse-tractusx/daps-registration-service/blob/2d437d9311d3d71a28d605ffe4dd2612f9a5a960/INSTALL.md?plain=1#L9).

Adding the repo is done with a one name and further helm commands use a separate name. This would lead do issues when copy-pasting the examples for local use.

## Expected

Helm repo names mentioned in install docs should match and be consistent.
Suggestion: Stick with `tractusx-dev` as name, since it contains all charts release in the GitHub org

**Comment by adkumar1** [comment]
Corrected in new PR https://github.com/eclipse-tractusx/daps-registration-service/pull/39 with commit https://github.com/eclipse-tractusx/daps-registration-service/commit/cb585f7301d03e774cf33e9ee30e59391148fd4a
