### ISSUE TITLE
`.tractusx` metafile is missing in the root of the repository

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/daps-registration-service#38]
# Description

[TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) describes a metadata file, that contains information about the product in this repository and any related repository. It is also used for automation on the whole GitHub org.
The `.tractusx` metadata file is missing

# Expected
File is present, and contains relevant product information

**Comment by adkumar1** [comment]
Added it in new PR  https://github.com/eclipse-tractusx/daps-registration-service/pull/39 with commit cb585f7301d03e774cf33e9ee30e59391148fd4a
